### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by marf** [Jeve-Stobs/lyrics-finder#1]
Hello,

I have tried to run test.js but it says:

`TypeError: Cannot read properties of undefined (reading 'split')`

Is the package currently working?

Thanks!

**Comment by Jeve-Stobs** [comment]
Hello! I believe this was due to an error where Google didn't return the lyrics, so there wasn't any html to parse. This has been fixed in https://github.com/Jeve-Stobs/lyrics-finder/commit/e71a30584a70e790aabf9b5c4bf6fbf7bfb85065
